### ISSUE TITLE
java.lang.Exception on taking photo on Android 8

### ISSUE THREAD

**Issue by RGBvision** [Yoonit-Labs/nativescript-yoonit-camera#36]
### If the demo apps cannot help and there is no issue for your problem, tell us about it
When taking a photo with startCapture('frame') console reports this:

```
System.err: java.lang.Exception: Stack trace
System.err:     at java.lang.Thread.dumpStack(Thread.java:1346)
System.err:     at androidx.camera.camera2.internal.CaptureSession.issueRepeatingCaptureRequests(CaptureSession.java:599)
System.err:     at androidx.camera.camera2.internal.CaptureSession.setSessionConfig(CaptureSession.java:166)
System.err:     at androidx.camera.camera2.internal.Camera2CameraImpl.updateCaptureSessionConfig(Camera2CameraImpl.java:914)
System.err:     at androidx.camera.camera2.internal.Camera2CameraImpl.lambda$onUseCaseInactive$6$Camera2CameraImpl(Camera2CameraImpl.java:562)
System.err:     at androidx.camera.camera2.internal.-$$Lambda$Camera2CameraImpl$L-qXzxII6_fhY_FN_HX18hvqHpE.run(Unknown Source:4)
System.err:     at androidx.camera.core.impl.utils.executor.SequentialExecutor$1.run(SequentialExecutor.java:110)
System.err:     at androidx.camera.core.impl.utils.executor.SequentialExecutor$QueueWorker.workOnQueue(SequentialExecutor.java:230)
System.err:     at androidx.camera.core.impl.utils.executor.SequentialExecutor$QueueWorker.run(SequentialExecutor.java:172)
System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
System.err:     at java.lang.Thread.run(Thread.java:764)
```

But photo saved successfully

### Which platform(s) does your issue occur on?
- Android 
- Android 8.0.0
- HTC 10 (mobile phone)

### Please, provide the following version numbers that your issue occurs with:

- CLI: 7.1.1
- Cross-platform modules: 7.1.0
- Runtime: @nativescript/android 7.0.1
- Plugin(s):
```
"dependencies": {
    "@nativescript-community/gps": "^2.1.5",
    "@nativescript-community/l": "^4.2.15",
    "@nativescript/core": "~7.1.0",
    "@nativescript/theme": "~2.3.0",
    "@nstudio/nativescript-floatingactionbutton": "^3.0.4",
    "@nstudio/nativescript-pulltorefresh": "^3.0.1",
    "@yoonit/nativescript-camera": "^2.0.0",
    "moment": "^2.29.1",
    "nativescript-app-tour": "^2.0.2",
    "nativescript-https": "^2.2.2",
    "nativescript-vibrate": "^4.0.1",
    "nativescript-windowed-modal": "file:./plugins/nativescript-windowed-modal-master/src"
  },
  "devDependencies": {
    "@nativescript/android": "7.0.1",
    "@nativescript/types": "7.1.0",
    "@nativescript/webpack": "~4.0.0",
    "node-sass": "^4.14.1"
  }
```

### Please, tell us how to recreate the issue in as much detail as possible. 
```
const {YoonitCamera} = require('@yoonit/nativescript-camera/Yoonit.Camera');

function cvLoaded(args) { 

    const cView = args.object; // <ContentView> in my XML
    yCam = new YoonitCamera();

    yCam.on('imageCaptured', (data) => {
        yCam.stopCapture();
        ImageSource.fromFile(data.image["path"]).then((img) => {
            const folder = knownFolders.documents().getFolder("orderPhotos").path;
            const fileName = moment().format('x') + '.jpg';
            const filePath = path.join(folder, fileName);
            const saved = img.saveToFile(filePath, "jpg");
            if (saved) {
                closeCallback(filePath);
            } else {
                
            }
        });
    });

    cView.content = yCam;

    yCam.requestPermission().then(() => {
        yCam.setLens('back');
        yCam.setOutputImageWidth("1000px");
        yCam.setOutputImageHeight("1000px");
        yCam.setSaveImageCaptured(true);
        yCam.preview();
    });
}

function onTakePhoto(args) {
    yCam.startCapture('frame');
}

```

**Comment by luiguild** [comment]
Just a question @RGBvision, in your sample code, why do you register the event and then you save the file again? Do you know that with this approach you are duplicating the file in storage?

In the image event, we offer an object with tree keys in the callback function, `path`, `source` and `binary` and every time that we capture a frame we process the file https://github.com/Yoonit-Labs/nativescript-yoonit-camera/blob/development/src/Yoonit.Camera.android.ts#L94

Maybe this can help you if you need to move the file instead get the path and save again.

**Comment by RGBvision** [comment]
@luiguild Yep, I know what you talking about... but... after taking a photo file not available if you don't save it programmatically.

**Comment by TeruyaHaroldo** [comment]
Hello @RGBvision

We are investigating and trying to reproduce the error. Can you please try to reproduce the error in the [`demo`](https://github.com/Yoonit-Labs/nativescript-yoonit-camera/tree/development/demo-vue) for us?

About the photo availability of the photo file, you can see in the [`demo`](https://github.com/Yoonit-Labs/nativescript-yoonit-camera/tree/development/demo-vue) how we use the `imageCaptured` event [here](https://github.com/Yoonit-Labs/nativescript-yoonit-camera/blob/ef794adf245ebb6ea9a1c801ec11b6da81837a50/demo-vue/app/components/App.vue#L168)

**Comment by RGBvision** [comment]
Demo works just fine. No errors in log on same device.

**Comment by luiguild** [comment]
@RGBvision could you please review your approach using the blob file or source that already provided by the callback to validate if this have any interference with this error?

**Comment by luiguild** [comment]
Any news @RGBvision? We can close this issue?

**Comment by RGBvision** [comment]
> Any news @RGBvision? We can close this issue?

Sorry, I'll be busy for the rest of the week. Then I'll try to make a simple app for testing. I will write about the test results on Sunday.

**Comment by RGBvision** [comment]
With v2.1.0 I can't reproduce this issue.
