### ISSUE TITLE
TypeError: Cannot read property 'forEach' of null

### ISSUE THREAD

**Issue by ramosestudiante** [Yoonit-Labs/nativescript-yoonit-camera#41]
### Which platform(s) does your issue occur on?
- Both 
- emulator
### Please, provide the following version numbers that your issue occurs with:

- CLI: 7.0.12
- Cross-platform modules: 7.0.13
- Plugin(s):
```
"dependencies": {
    "@nativescript/core": "^7.0.3",
    "@yoonit/nativescript-camera": "^2.1.0",
    "axios": "^0.21.1",
    "fastest-validator": "^1.9.0",
    "nativescript-ui-listview": "^9.1.0",
    "nativescript-vue": "^2.8.1",
    "nativescript-vue-fonticon": "^1.0.3",
    "vuex": "^3.5.1"
  },
  "devDependencies": {
    "@babel/core": "^7.11.6",
    "@babel/preset-env": "^7.11.5",
    "@nativescript/ios": "7.0.6",
    "@nativescript/android": "7.0.1",
    "@nativescript/webpack": "^3.0.4",
    "babel-loader": "^8.1.0",
    "nativescript-vue-template-compiler": "^2.8.1",
    "nativescript-worker-loader": "~0.12.1",
    "sass": "^1.26.10",
    "vue-loader": "^15.9.3"
  }
```
### Please, tell us how to recreate the issue in as much detail as possible. 
Occurs when you use YoonitCamera component and then call the $ navigate Back function and remount the component, then throw `TypeError error: Cannot read property 'forEach' of null`.

**Comment by luiguild** [comment]
Thanks for your contribution @ramosestudiante! We moving forward to deploy this fix in the next version :)
